### ISSUE TITLE
/varz flattened

### ISSUE THREAD

**Issue by derekcollison** [repejota/nats-mon#1]
I am proposing to flatten the /varz from its current form (http://demo.nats.io:8222/varz) and wanted to know if this is supported by you and give you a heads up in case it effects this app. So **info** and **options** will be flattened.

``` json
{
  "info": {
    "server_id": "2f78a1f80490c353b98c26b44c2538af",
    "version": "0.6.1.beta",
    "go": "go1.4.2",
    "host": "0.0.0.0",
    "port": 4222,
    "auth_required": false,
    "ssl_required": false,
    "max_payload": 1048576
  },
  "options": {
    "max_connections": 65536,
    "ping_interval": 120000000000,
    "ping_max": 2,
    "http_port": 8222,
    "ssl_timeout": 0.5,
    "max_control_line": 1024,
    "max_payload": 1048576
  },
  "start": "2015-07-23T18:29:56.147183034-04:00",
  "now": "2015-07-29T11:13:42.400200429-04:00",
  "uptime": "5d16h43m46s",
  "mem": 307027968,
  "cores": 8,
  "cpu": 0,
  "connections": 0,
  "routes": 0,
  "remotes": 0,
  "in_msgs": 25794407,
  "out_msgs": 25717955,
  "in_bytes": 796293027,
  "out_bytes": 793923044,
  "slow_consumers": 0
}
```

**Comment by repejota** [comment]
Sure! 
I'll keep an eye too on nats changes to see when this is introduced. And will change my calls to the new format ASAP. :)

Anyway, the next couple of days I'll be working mostly on the UI to provide true real-time to the monitor through ReactJS and get a nice prototype to add support for /connz and the remaining endpoints. So feel free to introduce this change.

Thanks for the notice!

**Comment by derekcollison** [comment]
Done, in master, not release tagged yet but soon.

**Comment by repejota** [comment]
Thanks! I'll keep an eye for the release, our next release will also implement sorted collections on the monitor grid too :)

**Comment by derekcollison** [comment]
That's great. gnatsd supports the sorting preferences with limits and offsets, so should be good to go!
